### ISSUE TITLE
[Transformer] We don't have an error when we try to transform an invalid index

### ISSUE THREAD

**Issue by FabienSalles** [cleverage/process-bundle#117]
## Description

The mapping transformer use the PropertyAccess Symfony component in order to set values.
In order to trigger exceptions when mappings are incorrect we need to configure the component properly : 
```
framework:
    property_access:
        throw_exception_on_invalid_index: true
        throw_exception_on_invalid_property_path: true
```
After this, we can see an exception when we have an invalid index but the second one i never trigger because if the property is not writable we set the value without the property access ```
https://github.com/cleverage/process-bundle/blob/v3.1-dev/Transformer/MappingTransformer.php#L144 

We need to remove the fallback with the array or trigger an exception before if the property does not exist
