### ISSUE TITLE
Mapping Transformer + Sf5 + old key syntax is failing

### ISSUE THREAD

**Issue by shavounet** [cleverage/process-bundle#126]
## Description

To be analysed : I found an issue with the old mapping syntax and Sf5
- failing line : https://github.com/cleverage/process-bundle/blob/v3.2-dev/Transformer/MappingTransformer.php#L141
- error `Transformation 'mapping' have failed: Symfony\Component\PropertyAccess\PropertyAccessor::isPropertyWritable(): Argument #1 ($object) must be of type object, array given`

```yaml
mapping:
  mapping:
    key1: ....            # <= this doesn't work anymore if input is an array 
    '[key2]': ....        # <= this is ok 
```

Maybe it's time to depreciate it ?

## Requirements

* Documentation updates
  - [ ] Reference
  - [ ] Cookbooks
  - [ ] Changelog
* [ ] Unit tests
