### ISSUE TITLE
Document the behavior implemented in TransformerTrait::getCleanedTransfomerCode

### ISSUE THREAD

**Issue by VincentChalnot** [cleverage/process-bundle#61]
Document the behavior allowed when declaring transformers:
```yaml
transformers:
    callback#1:
        callback: array_filter
    callback#2:
        callback: array_reverse
```
